language: haskell
ghc:
  - 7.4
  - 7.6
  - 7.8
addons:
  apt:
    packages:
      - libgmp-dev
      - libgtk2.0-dev
      - libcairo2-dev
      - libglib2.0-dev
before_install:
  - cabal install alex happy gtk2hs-buildtools 'Cabal >= 1.22.4.0'
